language: node_js

node_js:
    - "9"
    - "8"
    - "7"
    
branches:
    only:
        - master
        
before_install:
    - npm install -g gulp
    
script: 
    - gulp
    - gulp build
    - gulp update
    - gulp clean
    
notification:
    email:
        - warengonzaga.dev@gmail.com